version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: camile
      POSTGRES_PASSWORD: caftrainer2025
      POSTGRES_DB: caf_trainer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .                 # racine du repo
      dockerfile: backend/Dockerfile.dev
    working_dir: /app/backend
    env_file: .env
    depends_on: [postgres]
    volumes:
      - ./backend:/app/backend           # code + prisma en live
      - ./tsconfig.json:/app/tsconfig.json:ro
      - /app/backend/node_modules        # conserve node_modules du conteneur
    command: npm run dev
    ports:
      - "5000:5000"

volumes:
  pgdata: {}
