# backend/docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: caf_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: caf_trainer
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
